ARG UI_IMAGE=ghcr.io/brainminds-dataportal/zaviewer:latest-ui
FROM ${UI_IMAGE}

WORKDIR /usr/share/nginx

ARG OCI_TITLE=ghcr.io/brainminds-dataportal/zaviewer
ARG OCI_DESCRIPTION="ZAViewer User Interface + minimal server for region editor"
ARG OCI_SOURCE=https://github.com/brainminds-dataportal/zaviewer
ARG OCI_VERSION=dev-ed
ARG OCI_CREATED=1970-01-01T00:00:00Z
ARG OCI_REVISION=unknown

#server script to store edited SVG
COPY ./admin/SVG.php /usr/share/nginx/html/admin/

#nginx config files for server-side include and fastcgi
COPY ./extension/nginx_extra.conf /etc/nginx/conf.d/nginx_extra.conf 
COPY ./extension/nginx_php.conf /etc/nginx/conf.d/nginx_php.conf 

#install php & required modules + fastcgi, 
#disable default nginx conf,
#append option to start nginx in foreground
RUN apk update  && \
apk add php84 php84-mbstring php84-dom php84-xml php84-fpm php84-opcache  && \
mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.confBACK && \
echo "daemon off;" >> /etc/nginx/nginx.conf

RUN find /usr/share/nginx/html/ -type d -exec chmod 755 {} \;
RUN find /usr/share/nginx/html/ -type f -exec chmod 644 {} \;

LABEL org.opencontainers.image.title="${OCI_TITLE}" \
      org.opencontainers.image.description="${OCI_DESCRIPTION}" \
      org.opencontainers.image.source="${OCI_SOURCE}" \
      org.opencontainers.image.url="${OCI_SOURCE}" \
      org.opencontainers.image.version="${OCI_VERSION}" \
      org.opencontainers.image.created="${OCI_CREATED}" \
      org.opencontainers.image.revision="${OCI_REVISION}"


EXPOSE 80

#run php-fpm as daemon and nginx in foreground.
CMD php-fpm84 -D; nginx;
