# temporary image used as build environment
FROM node:24-trixie-slim AS build


WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

# copy required files from context
COPY package.json ./
COPY package-lock.json ./
#copy npmrc template, and any existing .npmrc
COPY .npmrc* ./

# For github package registry access: if a token is supplied, use it to create (possibly overwrite) local .npmrc 
ARG PACKAGEREAD_TOKEN
RUN if [ ! -z "${PACKAGEREAD_TOKEN}" ]; then (cat .npmrc_template ; echo '${PACKAGEREAD_TOKEN}') > .npmrc ; fi


# download and install node modules
RUN npm ci

#
RUN rm .npmrc

#copy sources
COPY . ./

#generate ZAViewer bundles
RUN npm run build


# production environment
FROM nginx:1.30-alpine

ARG OCI_TITLE=ghcr.io/brainminds-dataportal/zaviewer
ARG OCI_DESCRIPTION="ZAViewer User Interface"
ARG OCI_SOURCE=https://github.com/brainminds-dataportal/zaviewer
ARG OCI_VERSION=dev-ui
ARG OCI_CREATED=1970-01-01T00:00:00Z
ARG OCI_REVISION=unknown

LABEL org.opencontainers.image.title="${OCI_TITLE}" \
      org.opencontainers.image.description="${OCI_DESCRIPTION}" \
      org.opencontainers.image.source="${OCI_SOURCE}" \
      org.opencontainers.image.url="${OCI_SOURCE}" \
      org.opencontainers.image.version="${OCI_VERSION}" \
      org.opencontainers.image.created="${OCI_CREATED}" \
      org.opencontainers.image.revision="${OCI_REVISION}"

# copy generated bundles and assets from building stage image
COPY --from=build /app/dist/ /usr/share/nginx/html/

RUN find /usr/share/nginx/html/ -type d -exec chmod 755 {} \;
RUN find /usr/share/nginx/html/ -type f -exec chmod 644 {} \;

# link to configuration descriptor used when displaying data located in mounted directory
RUN ln -s /usr/share/nginx/html/data/viewer.json /usr/share/nginx/html/viewer.json

# port which NginX listens to 
EXPOSE 80
