FROM python:3.12-bookworm

ARG OCI_TITLE=ghcr.io/brainminds-dataportal/zaviewer
ARG OCI_DESCRIPTION="ZAViewer Deep Zoom Images preparation utility"
ARG OCI_SOURCE=https://github.com/brainminds-dataportal/zaviewer
ARG OCI_VERSION=dev-prepimg
ARG OCI_CREATED=1970-01-01T00:00:00Z
ARG OCI_REVISION=unknown

RUN mkdir -p /usr/src/app/scripts
WORKDIR /usr/src/app/scripts
COPY . .

COPY requirements.prepDZIImages.txt .

RUN pip install --upgrade pip setuptools wheel
RUN pip install -r requirements.prepDZIImages.txt

RUN git clone https://github.com/openzoom/deepzoom.py.git && \
cd deepzoom.py && \
python setup.py install && \
cd ..


WORKDIR /usr/src/app

ENTRYPOINT ["python", "./scripts/prepareDZImages.py"]

LABEL org.opencontainers.image.title="${OCI_TITLE}" \
      org.opencontainers.image.description="${OCI_DESCRIPTION}" \
      org.opencontainers.image.source="${OCI_SOURCE}" \
      org.opencontainers.image.url="${OCI_SOURCE}" \
      org.opencontainers.image.version="${OCI_VERSION}" \
      org.opencontainers.image.created="${OCI_CREATED}" \
      org.opencontainers.image.revision="${OCI_REVISION}"
